// Code generated by "encli generate mock"; DO NOT EDIT.
// source: internal/query/user_post/repository/user_post_repository.go
//
// このファイルは "encli generate mock" により自動生成されました。
// 手動で編集しないでください。

package mock

import (
	"github.com/ensoria/ensoria-template/internal/query/user_post/record"
	"github.com/ensoria/testutil/pkg/mock"
)

type UserPostRepositoryMock struct {
	*mock.Mock
}

func NewUserPostRepositoryMock() *UserPostRepositoryMock {
	return &UserPostRepositoryMock{Mock: mock.New()}
}

func (m *UserPostRepositoryMock) GetByID(p0 int64) *record.UserPostRecord {
	r := m.Called("GetByID", p0)
	return mock.Get[*record.UserPostRecord](r, 0)
}
