// Code generated by "encli generate mock"; DO NOT EDIT.
// source: internal/module/user/service/user_service.go
//
// このファイルは "encli generate mock" により自動生成されました。
// 手動で編集しないでください。

package mock

import (
	"github.com/ensoria/ensoria-template/internal/module/user/model"
	"github.com/ensoria/testutil/pkg/mock"
)

type UserServiceMock struct {
	*mock.Mock
}

func NewUserServiceMock() *UserServiceMock {
	return &UserServiceMock{Mock: mock.New()}
}

func (m *UserServiceMock) GetById(p0 int64) (*model.User, error) {
	r := m.Called("GetById", p0)
	return mock.Get[*model.User](r, 0), mock.Get[error](r, 1)
}

func (m *UserServiceMock) GetPostContent(p0 string) (string, error) {
	r := m.Called("GetPostContent", p0)
	return mock.Get[string](r, 0), mock.Get[error](r, 1)
}

func (m *UserServiceMock) Something() string {
	r := m.Called("Something")
	return mock.Get[string](r, 0)
}
