// Code generated by "encli generate mock"; DO NOT EDIT.
// source: internal/module/user/repository/user_repository.go
//
// このファイルは "encli generate mock" により自動生成されました。
// 手動で編集しないでください。

package mock

import (
	"github.com/ensoria/ensoria-template/internal/module/user/model"
	"github.com/ensoria/testutil/pkg/mock"
)

type UserRepositoryMock struct {
	*mock.Mock
}

func NewUserRepositoryMock() *UserRepositoryMock {
	return &UserRepositoryMock{Mock: mock.New()}
}

func (m *UserRepositoryMock) GetByID(p0 int64) (*model.User, error) {
	r := m.Called("GetByID", p0)
	return mock.Get[*model.User](r, 0), mock.Get[error](r, 1)
}
