// Code generated by "encli generate mock"; DO NOT EDIT.
// source: internal/module/order/repository/order_repository.go
//
// このファイルは "encli generate mock" により自動生成されました。
// 手動で編集しないでください。

package mock

import (
	"github.com/ensoria/ensoria-template/internal/module/order/model"
	"github.com/ensoria/testutil/pkg/mock"
)

type OrderRepositoryMock struct {
	*mock.Mock
}

func NewOrderRepositoryMock() *OrderRepositoryMock {
	return &OrderRepositoryMock{Mock: mock.New()}
}

func (m *OrderRepositoryMock) FindByID(p0 uint) (*model.Order, error) {
	r := m.Called("FindByID", p0)
	return mock.Get[*model.Order](r, 0), mock.Get[error](r, 1)
}

func (m *OrderRepositoryMock) Save(p0 *model.Order) error {
	r := m.Called("Save", p0)
	return mock.Get[error](r, 0)
}
