// Code generated by "encli generate mock"; DO NOT EDIT.
// source: internal/module/post/service/post_service.go
//
// このファイルは "encli generate mock" により自動生成されました。
// 手動で編集しないでください。

package mock

import (
	"github.com/ensoria/ensoria-template/internal/module/post/dto"
	"github.com/ensoria/testutil/pkg/mock"
)

type PostServiceMock struct {
	*mock.Mock
}

func NewPostServiceMock() *PostServiceMock {
	return &PostServiceMock{Mock: mock.New()}
}

func (m *PostServiceMock) GetPost() *dto.Post {
	r := m.Called("GetPost")
	return mock.Get[*dto.Post](r, 0)
}
