// Code generated by "encli generate mock"; DO NOT EDIT.
// source: internal/module/order/service/order_service.go
//
// このファイルは "encli generate mock" により自動生成されました。
// 手動で編集しないでください。

package mock

import (
	"github.com/ensoria/ensoria-template/internal/module/order/dto"
	"github.com/ensoria/testutil/pkg/mock"
)

type OrderServiceMock struct {
	*mock.Mock
}

func NewOrderServiceMock() *OrderServiceMock {
	return &OrderServiceMock{Mock: mock.New()}
}

func (m *OrderServiceMock) GetOrder() (*dto.Order, error) {
	r := m.Called("GetOrder")
	return mock.Get[*dto.Order](r, 0), mock.Get[error](r, 1)
}
